name: deploy-container

on: #what events are we watching for
  push: #when we push to master
    branches:
      - main
    paths: #only run this workflow when these files change inside container
      - './container/**'

defaults:
  run:
    working-directory: container #sets execution env to container directory

jobs:
  build:
    runs-on: ubuntu-latest #runs on ubuntu

    steps:
      - uses: actions/checkout@v2 #checks out the repo
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2 #uses aws cli
      - run: aws s3 sync dist s3://${{ secrets.AWS_BUCKET_NAME }}/container/latest #syncs dist folder to s3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ''
